### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by M-Husein** [DoomyTheFroomy/GeoLocation#6]
Hi,
Thanks for share your code.

I want to use, but I don't know how to use tour code, please give me guide.

Thanks

**Comment by DoomyTheFroomy** [comment]
@M-Husein thanks for your request! I really need to enhance the Readme! :smirk: 

Until this you can have a look at the tests! There are some use cases published! 

If you want you can give a PR! :white_check_mark:

**Comment by M-Husein** [comment]
Thanks For Reply ;)

Where can I find some published use cases? give me link please :)

All right, I'll do the PR :+1:

**Comment by DoomyTheFroomy** [comment]
@M-Husein here is the [test file](https://github.com/DoomyTheFroomy/GeoLocation/blob/develop/test/geolocation-test.js)

**Comment by DoomyTheFroomy** [comment]
@M-Husein I have updated the [README](https://github.com/DoomyTheFroomy/GeoLocation#how-to-use) hope this helps
